version: '3.9'
services:
  app:
    container_name: app
    build: .
    env_file:
      - .development.env
    environment:
      POSTGRES_HOST: 'postgres'
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: 'nest_pg'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    restart: always
